  <?php
    $request = $this->getRequest();
    $module = $request->getModuleName();
    $controller = $request->getControllerName();
    $action = $request->getActionName();

    //if($module == 'checkout' && $controller == 'cart' && $action == 'index')
      if(1)
    { ?>
         <!-- 6 options zcfasfd-->
         <div class="midsection product-list deine">
           <div class="custom-container">
             <h3 class="title"><span>Deine Vorteile</span></h3>
                 <ul class="botmlist">
               <li class="vegan-blk">
                 <span class="circle-blk"><img src="<?php echo $this->getViewFileUrl('images/svg/vigan1.svg'); ?>" alt="" /></span>
                 <h4>100% Vegan</h4>
                 <p>Frei von Inhaltsstoffen tierischen Ursprungs. Alle Formulierungen sind vegan.</p>
               </li>
               <li class="deine2-blk">
                 <span class="circle-blk"><img src="<?php echo $this->getViewFileUrl('images/svg/rabit1.svg'); ?>" alt="" /></span>
                 <h4>Ohne Tierversuche</h4>
                 <p>Hergestellt ohne Tierleid. Alle Produkte und Inhaltsstoffe sind frei von Tierversuchen.</p>
               </li>
               <li class="versand-blk">
                 <span class="circle-blk"><img src="<?php echo $this->getViewFileUrl('images/svg/ship-truck1.svg'); ?>" alt="" /></span>
                 <h4>Kostenloser Versand</h4>
                 <p>Deine Bestellung erhälst du immer versandkostenfrei. Ohne Mindest- bestellwert.</p>
               </li>
               <li class="heute-blk">
                 <span class="circle-blk"><img src="<?php echo $this->getViewFileUrl('images/svg/clock1.svg'); ?>" alt="" /></span>
                 <h4>Heute bestellt Morgen geliefert</h4>
                 <p>Bestellungen bis 14:00 werden noch gleichen Tags mit A-Post versandt.</p>
               </li>
               <li class="kauf-blk">
                 <span class="circle-blk"><img src="<?php echo $this->getViewFileUrl('images/svg/page1.svg'); ?>" alt="" /></span>
                 <h4>Kauf auf Rechnung</h4>
                 <p>Einfach und bequem auf Rechnung bestellen. Ohne Gebühren und Zusatzkosten.</p>
               </li>
               <li class="tage-blk">
                 <span class="circle-blk"><img src="<?php echo $this->getViewFileUrl('images/svg/reload1.svg'); ?>" alt="" /></span>
                 <h4>30 Tage Rückgaberecht</h4>
                 <p>Ungeöffnete Ware kannst Du innert 30 Tagen an uns zurücksenden.</p>
               </li>
             </ul>
           </div>
         </div>
        <br/><br/>
    <?php }
?>
<?php
    if($module == 'checkout' && $controller != 'cart' && $action == 'index')
    { ?>
		<style type="text/css">.upper_footer { display: none; } .authentication-wrapper { display: none; }</style>
	<?php }
?>
	<div class="upper_footer">
		<div class="custom-container">
			<div class="row">
				<div class="col-md-4 follow-blk-sm">
					<h3 class="footer-heading">Folge <span>uns</span></h3>
					<ul class="social_ul">
						<li><a href="javascript:void(0)"><i class="fa fa-facebook-f"></i></a></li>
						<li><a href="javascript:void(0)"><i class="fa fa-pinterest"></i></a></li>
						<li><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
						<li><a href="javascript:void(0)"><i class="fa fa-instagram"></i></a></li>
					</ul>
				</div>
				<div class="col-md-4 newsletter-blk-sm">
					<h3 class="footer-heading">Newsletter <span>abonnieren<span></h3>

					 <?php
							echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_middle')->toHtml();
					?>
				</div>
				<div class="col-md-4 kontact-blk-sm">
					<h3 class="footer-heading">Kontakt</h3>
					<p><a href="mailto:contact@exurbecosmetics.com">contact@exurbecosmetics.com</a></p>
					<p><a href="tel:41445520905">Tel. +41445520905</a></p>
				</div>
			</div>
		</div>
	</div>

	<div class="middle_footer"cvbv>
		<div class="custom-container">
			<p>SICHER EINKAUFEN. SICHER BEZAHLEN. SCHNELL GELIEFERT.</p>
			<ul class="cardlist">
				<li><img src="<?php echo $this->getViewFileUrl('images/pay1.jpg'); ?>" alt=""></li>
				<li class="payment-size"><img src="<?php echo $this->getViewFileUrl('images/svg/flag/mastro1.svg'); ?>" alt=""></li>
				<li class="payment-size"><img src="<?php echo $this->getViewFileUrl('images/svg/flag/american2.svg'); ?>" alt=""></li>
				<li class="payment-size"><img src="<?php echo $this->getViewFileUrl('images/svg/flag/visa3.svg'); ?>" alt=""></li>
				<li class="payment-size"><img src="<?php echo $this->getViewFileUrl('images/svg/flag/paypal4.svg'); ?>" alt=""></li>
				<li><img src="<?php echo $this->getViewFileUrl('images/pay6.jpg'); ?>" alt=""></li>
				<li><img src="<?php echo $this->getViewFileUrl('images/pay7.jpg'); ?>" alt=""></li>
				<li><img src="<?php echo $this->getViewFileUrl('images/pay8.jpg'); ?>" alt=""></li>
			</ul>
		</div>
	</div>
	<div class="bottom_footer">
		<div class="custom-container">
			<div class="row">
				<div class="col-sm-1">
					<a class="footer_toggle" href="javascript:void(0)"><i class="fa fa-angle-down"></i></a>
				</div>
				<div class="col-sm-2">
					<h5>Über uns</h5>
					<ul class="bottom_ul">
						<li><a href="#">Über uns</a></li>
						<li><a href="#">Standorte</a></li>
					</ul>
				</div>
				<div class="col-sm-2">
					<h5>Für dich</h5>
					<ul class="bottom_ul">
						<li><a href="#">Fragen und Antworten</a></li>
						<li><a href="#">Kontakt</a></li>
						<li><a href="#">Jobs</a></li>
					</ul>
				</div>
				<div class="col-sm-2">
					<h5>Partner & Presse</h5>
					<ul class="bottom_ul">
						<li><a href="#">Partnerschaft</a></li>
						<li><a href="#">Presse</a></li>
					</ul>
				</div>
				<div class="col-sm-2">
					<h5>Rechtliches</h5>
					<ul class="bottom_ul">
						<li><a href="#">Geschäftsbedingungen</a></li>
						<li><a href="#">Datenschutz</a></li>
						<li><a href="#">Impressum</a></li>
					</ul>
				</div>
				<div class="col-sm-3"><p>© 2018 abVentures AG. Alle Rechte vorbehalten.</p></div>
			</div>
		</div>
	</div>
<style type="text/css">
	span.input-number-decrement { font-size: 24px; }
	span.input-number-increment { font-size: 24px; }
</style>
<script>


	jQuery(document).ready(function(){
		jQuery('.footer_toggle').click(function(){

			jQuery('.bottom_footer .bottom_ul').toggle(500);

		});
		jQuery('.input-number-decrement').click(function() {
	      var $input = jQuery(this).parents('.input-number-group').find('.input-number');
	      var val = parseInt($input.val(), 10);
	      $input.val(val + 1);
	    });

	    jQuery('.input-number-increment').click(function() {
	      var $input = jQuery(this).parents('.input-number-group').find('.input-number');
	      var val = parseInt($input.val(), 10);
	      $input.val(val - 1);
	    });

      jQuery("#bottom").on("click" ,function(){
      //  alert(jQuery(document).height());
      var scrolled=jQuery(document).height();
      jQuery('html,body').animate({ scrollTop: jQuery("#cat_down").offset().top }, 1000);
      });

      jQuery(document).on('click', '#parent_filter_btn', function(event) {
        event.preventDefault();
        /* Act on the event */
        //alert("ok");
        var sp_class=jQuery(this).find('.glyphicon').attr('class');
        if(sp_class=="glyphicon glyphicon-menu-down")
        {
                  jQuery(this).parent().find('.glyphicon').attr('class','glyphicon glyphicon-menu-up');
        }else{
          jQuery(this).parent().find('.glyphicon').attr('class','glyphicon glyphicon-menu-down');
        }
        jQuery('.block-content.filter-content').toggleClass('show_div_RG');
      });

	});

</script>
