<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div id="minicart_mobile" data-block="minicart" class="minicart-wrapper dropdown" mobile>


    <span id="mini_action" class="action showcart cart-icon" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <!-- <span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span> -->
        <span class="counter qty empty"
              data-bind="css: { empty: cart().summary_count < 0 }, blockLoader: isLoading">
              <!-- ko ifnot: cart().summary_count > 0 -->
            <span class="counter-number"> 0 </span>
            <!--/ko -->
            <!-- ko if: cart().summary_count > 0 -->
          <span class="counter-number"><!-- ko text: cart().summary_count --><!-- /ko --></span>
          <!--/ko -->
            <span class="counter-label">

            </span>

        </span>
    </span>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>

    <?php endif ?>
    <script>
        window.checkout1 = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;

        jQuery(document).ready(function($) {
          $('#minicart_mobile').click(function(event) {
            /* Act on the event */
            //alert("ok");
            window.location.replace(window.checkout1.shoppingCartUrl)
          });
        });
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>

</div>
