<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty" no_items>
    <?php echo $block->getChildHtml('checkout_cart_empty_widget'); ?>
    <p><?php /* @escapeNotVerified */ echo __('Your Shopping Basket is Empty.') ?></p>
	<p><?php /* @escapeNotVerified */ echo __('Get started and fill your shopping cart with the latest make-up trends.') ?></p>
    <?php //echo __('TO THE NEWS') ?>
    <p><?php /* @escapeNotVerified */ echo __('<a href="%1">'. __('TO THE NEWS').'</a>',
            $block->escapeUrl($block->getContinueShoppingUrl())) ?></p>
    <?php echo $block->getChildHtml('shopping.cart.table.after'); ?>
    <div class="full-img-panel"><div class="thankimg"><img src="<?php echo $this->getViewFileUrl('images/thankyoubanner.jpg'); ?>" alt="" />
    <!-- <img src="<?php echo $this->getViewFileUrl('images/thankyou.jpg'); ?>" alt="" /></div> -->
</div></div>
<?php echo  $this->getLayout()->createBlock("Favourite\FProduct\Block\FProduct")->setTemplate("Favourite_FProduct::fproduct.phtml")->toHtml(); ?>
