<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$blockObj= $block->getLayout()->createBlock('Favourite\FProduct\Block\CProduct');
?>
<div class="cart item">
    <div class="item-info">
        <!--<td data-th="<?php //echo $block->escapeHtml(__('Item')); ?>" class="col item">-->
        <div class="product-item-left">
            <div class="product-item-image">
                <?php if ($block->hasProductUrl()):?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
                       title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
                       tabindex="-1"
                       class="product-item-photo">
                <?php else:?>
                    <span class="product-item-photo">
                <?php endif;?>
                <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
                <?php if ($block->hasProductUrl()):?>
                     </span>
                    </a>
                <?php else: ?>

                <?php endif; ?>
            </div>
        </div>
        <div class="product-item-right">
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?php echo $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <div class="cat-name">
                <?php $categories = $product->getCategoryIds();
                      $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                   
                      foreach($categories as $parent_category_id)
                      {
                        $subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($parent_category_id);
                        $subcats = $subcategory->getChildrenCategories();
                        if(count($subcats) <= 0){
                            echo $subcategory->getName();
                        }									   
                  }  
                // echo "<pre>";print_r($categories); ?>
              </div>
                <?php if ($_options = $block->getOptionList()):?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        <!--</td>-->

        <?php if ($canApplyMsrp): ?>
            <div class="col msrp" data-th="<?php //echo $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                    </a>
                </span>
            </div>
        <?php else: ?>
            <div class="col price" data-th="<?php //echo $block->escapeHtml(__('Price')); ?>">
                <?php //echo $block->getUnitPriceHtml($_item); ?>
            </div>
        <?php endif; ?>
        <div class="col qty" data-th="<?php //echo $block->escapeHtml(__('Qty')); ?>">
            <div class="field qty">
                <label class="label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                    <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
                </label>

                <div class="control qty input-group input-number-group">
                    <div class="input-group-button">
                        <span class="input-number-decrement"><a href="javascript: void(0);"><i class="fa fa-angle-up" aria-hidden="true"></i></a></span>
                    </div>
                    <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                           name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                           data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                           value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                           class="input-text qty input-number"
                           maxlength="12"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                    <div class="input-group-button">
                        <span class="input-number-increment"><a href="javascript: void(0);"><i class="fa fa-angle-down" aria-hidden="true"></i></a></span>
                  </div>
                </div>
            </div>
        </div>

        <div class="col subtotal" data-th="<?php //echo $block->escapeHtml(__('Subtotal'));?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?php echo $block->getRowTotalHtml($_item); ?>
            <?php endif; ?>
        </div>

    <div class="item-actions">
        <!--<td colspan="100">-->
            <div class="actions-toolbar">
                <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
            </div>
        <!--</td>-->
    </div>
</div>
</div>
</div>
<script>
    // window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
    // window.customerData = window.checkoutConfig.customerData;
    var a=["dfsd"];
    window.checkoutConfig.category="asas";
    //console.log(window.checkoutConfig.customerData);
</script>
