<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<form class="form password forget"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
      method="post"
      id="form-validate1"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="field note"><?php /* @escapeNotVerified */ echo __('Please enter your email address below to receive a password reset link.'); ?></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" placeholder="E-Mail-Adresse" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
            <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" id="forget" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>

</form>


<script type="text/javascript">
    // require(["jquery","mage/validation"],function($) {
    //     $(document).ready(function() {
    //         var customurl = "<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>";
    //
    //
    //
    //         $(document).on('click', '#forget', function(event) {
    //           event.preventDefault();
    //           /* Act on the event */
    //           $.ajax({
    //               url: customurl,
    //               type: 'POST',
    //               dataType: 'json',
    //               data: $('#form-validate1').serialize(),
    //               beforeSend: function() {
    //                 $('body').trigger('processStart');
    //               },
    //               complete: function(response) {
    //             //  console.log(response);
    //              $('body').trigger('processStop');
    //               },
    //               error: function (xhr, status, errorThrown) {
    //                 //  console.log('Error happens. Try again.');
    //               }
    //           });
    //         });
    //     });
    // });

</script>
