<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<!-- <div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Registered Customers') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">

    </div>
</div> -->
<div class="form-full-section">
<div class="row">
<div class="col-md-12">
<form class="form form-login"
      action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
      method="post"
      id="login-form-customer"
      data-mage-init='{"validation":{}}'>
    <?php echo $block->getBlockHtml('formkey'); ?>
    <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <!--<div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>-->
        <div class="field email required">
            <div class="control">
                <input name="login[username]" placeholder="E-Mail-Adresse" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email-customer" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
            </div>

			<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('E-Mail-Adresse') ?></span></label>
        </div>
        <div class="field password required">
            <div class="control">
                <input name="login[password]" placeholder="Passwort" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass-customer" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}">
            </div>
			<label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Passwort') ?></span></label>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
        <div class="actions-toolbar">
		<div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
            <div class="primary"><button type="submit" class="action login primary" name="send" id="send-customer"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>

        </div>
    </fieldset>
</form>
	<h3><a href="<?=$this->getBaseUrl()?>customer/account/create/">Noch keinen exurbe Account?</a></h3>
</div>
</div>
</div>
