<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="registration" class="registration-blk"  data-bind="scope:'registration'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#registration": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "registration": {
                            "component": "Magento_Checkout/js/view/registration",
                            "config": {
                                "registrationUrl": "<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl(); ?>",
                                "email": "<?php /* @escapeNotVerified */ echo $block->getEmailAddress(); ?>"
                            }
                        }
                    }
                }
            }
        }
    </script>
</div>

<div class="full-img-panel">
 <div class="thankimg"><img src="<?php echo $this->getViewFileUrl('images/thankyoubanner.jpg'); ?>" alt="" />
 <img src="<?php echo $this->getViewFileUrl('images/thankyou.jpg'); ?>" alt="" /></div>
</div>


