<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$blockObj= $block->getLayout()->createBlock('Favourite\FProduct\Block\CProduct');
?>

<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
  <div class="page-title-wrapper success-title">
    <h1 class="page-title">Vielen Dank für deine Bestellung!</h1>
  </div>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p class="order-no-blk"><?php echo __('Deine Bestellnummer lautet: %1', sprintf('<div><a href="%s" class="order-number"><span>%s<span></a></div>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p class="order-no-blk"><?php echo __('Deine Bestellnummer lautet: <div class="order-number"><span>%1</span></div>', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('Du erhältst in wenigen Augenblicken eine Bestellbestätigung per E-Mail mit weiteren Informationen und einem Link,
<span>um die Bestellung weiterverfolgen zu können.</span>') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar center-con-blk">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>

</div>
<?php if($blockObj->customer_log_in()){ ?>
<div class="full-img-panel">
 <div class="thankimg"><img src="<?php echo $this->getViewFileUrl('images/thankyoubanner.jpg'); ?>" alt="" />
 <img src="<?php echo $this->getViewFileUrl('images/thankyou.jpg'); ?>" alt="" /></div>
</div>
<?php }?>
