<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Review\Block\Form
 */
?>
<div class="product_review_tab2" id="product_review-form">
    <!-- <p class="write_a_review"><?php /* @escapeNotVerified */ echo __('SCHREIBE DEINE EIGENE BEWERTUNG') ?></p> -->
    <div class="block review-add">
        <!-- <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Write Your Own Review') ?></strong></div> -->
        <div class="block-content">
            <?php if ($block->getAllowWriteReviewFlag()): ?>
            <form action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
                <?php echo $block->getBlockHtml('formkey'); ?>
                <?php echo $block->getChildHtml('form_fields_before')?>
                <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
                    <!--<div class="legend review-legend">
                        <p>
                             <?php /* @escapeNotVerified */ echo __("Du bewertest den Artikel: "); ?> -->
                            <!-- <strong><?php echo $block->escapeHtml($block->getProductInfo()->getName()) ?></strong>
                        </p>
                    </div>-->
                    <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                    <span id="input-message-box"></span>
                    <fieldset class="field required review-field-ratings">
                        <h3 class="rating_title"><span><?php /* @escapeNotVerified */ echo __('Wie bewertest du diesen Artikel?') ?><span></h3>
                        <div class="control">
                            <div class="nested" id="product-review-table">
                                <?php foreach ($block->getRatings() as $_rating): ?>
                                    <div class="field choice review-field-rating">
                                        <label class="rating_name" id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                                        <div class="control review-control-vote">
                                        <?php $options = $_rating->getOptions();?>
                                        <?php $iterator = 1; foreach ($options as $_option): ?>
                                            <input
                                                type="radio"
                                                name="ratings[<?php /* @escapeNotVerified */ echo $_rating->getId() ?>]"
                                                id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                                value="<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                                                class="radio"
                                                data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
                                                aria-labelledby="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label" />
                                            <label
                                                class="rating-<?php /* @escapeNotVerified */ echo $iterator; ?>"
                                                for="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                                title="<?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?>"
                                                id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label">
                                                <span><?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?></span>
                                            </label>
                                        <?php $iterator++; ?>
                                        <?php endforeach; ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                        </div>
                    </fieldset>
                <?php endif ?>
                    <div class="field review-field-nickname required">
                        <div class="control">
                            <input type="text" name="nickname" placeholder="Nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
                        </div>
						<label for="nickname_field" class="txt_label"><span><?php /* @escapeNotVerified */ echo __('Nickname') ?></span></label>
                    </div>
                    <div class="field review-field-summary required">
                        <div class="control">
                            <input type="text" placeholder="Title" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
                        </div>
						<label for="summary_field" class="txt_label"><span><?php /* @escapeNotVerified */ echo __('Title') ?></span></label>
                    </div>
                    <div class="field review-field-text required">
                        <div class="control">
                            <textarea name="detail" placeholder="Review" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                        </div>
						<label for="review_field" class="txt_label"><span><?php /* @escapeNotVerified */ echo __('Review') ?></span></label>
                    </div>
                </fieldset>
                <div class="actions-toolbar review-form-actions">
                    <div class="primary actions-primary">
                        <button type="submit" class="action submit primary my-btn"><span><?php /* @escapeNotVerified */ echo __('Submit Review') ?></span></button>
                    </div>
                </div>
            </form>
            <?php else: ?>
                <div class="message info notlogged" id="review-form">
                    <div>
                        <?php /* @escapeNotVerified */ echo __('Only registered users can write reviews. Please, <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()) ?>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>
<script type="text/javascript">
require([
    "jquery",
    "mage/mage"
],function($) {
    $(document).ready(function() {
        $('#form_id').mage(
            'validation',
            {
                submitHandler: function(form) {
                    $.ajax({
                        url: "<?php /* @escapeNotVerified */ echo $block->getAction() ?>",
                        data: $('#form_id').serialize(),
                        type: 'POST',
                        dataType: 'json',
                        showLoader: true,
                        beforeSend: function() {
                            // show some loading icon
                        },
                        success: function(data, status, xhr) {
                            // data contains your controller response
                        },
                        error: function (xhr, status, errorThrown) {
                            console.log('Error happens. Try again.');
                            console.log(errorThrown);
                        }
                    });
                }
            }
        );
    });
});
</script>
