<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="product_review_tab1">
<!--<p class="review_list"><?php /* @escapeNotVerified */ echo __('BEWERTUNG') ?></p>-->
<div id="product-review-container" data-role="product-review"></div>
</div>
<?php echo $block->getChildHtml(); ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?php /* @escapeNotVerified */ echo $block->getProductReviewUrl(); ?>"
            }
        }
    }
</script>
