
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$statiContenteUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_STATIC); ?>
<div class="vegan-free-blk"><img src='<?=$statiContenteUrl?>frontend/Magento/Exurbe/en_US/images/titebar.jpg' class="img-responsive" alt=""><h3 class="heart-icon"><span></span></h3></div>
