	<div id="carousel-example-generic2" class="carousel slide mobile_insta_slider" data-ride="carousel" >
		<!-- Indicators -->
		<!-- <ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
		</ol> -->

		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<img src="<?php echo $this->getViewFileUrl('images/teil1.jpg'); ?>" class="img-responsive" alt="" />
				<div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
			</div>
			<div class="item">
				<img src="<?php echo $this->getViewFileUrl('images/teil2.jpg'); ?>" class="img-responsive" alt="" />
				<div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
			</div>
			<div class="item">
				<img src="<?php echo $this->getViewFileUrl('images/teil3.jpg'); ?>" class="img-responsive" alt="" />
				<div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
			</div>
			<div class="item">
				<img src="<?php echo $this->getViewFileUrl('images/teil4.jpg'); ?>" class="img-responsive" alt="" />
				<div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
			</div>
			<div class="item">
				<img src="<?php echo $this->getViewFileUrl('images/teil5.jpg'); ?>" class="img-responsive" alt="" />
				<div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
			</div>
		</div>

		<!-- Controls -->
		<a class="left carousel-control" href="#carousel-example-generic2" role="button" data-slide="prev">
			<img src="<?php echo $this->getViewFileUrl('images/prev.png'); ?>" alt="" />
		</a>
		<a class="right carousel-control" href="#carousel-example-generic2" role="button" data-slide="next">
			<img src="<?php echo $this->getViewFileUrl('images/next.png'); ?>" alt="" />
		</a>
	</div>