<?php
/** @var Magenest\InstagramShop\Block\Adminhtml\System\Config\Form\AuthButton $block */
$buttonLabel = $block->getButtonLabel();
$url = $block->getButtonUrl();
$buttonHtmlId = $block->getHtmlId();
?>
<a data-ui-id="button-get-authorization-instagram" class="action-default scalable action-save action-secondary"
   id="<?= $buttonHtmlId ?>">
    <?= $block->escapeHtml($buttonLabel) ?>
</a>
<script>
    require(['jquery'], function ($) {
        $('#<?=$buttonHtmlId?>').on('click', function () {
            var clientId = $('input#magenest_instagram_shop_instagram_client_id').val();
            var clientSecret = $('input#magenest_instagram_shop_instagram_client_secret').val();

            $('body').loader('show');
            window.location.href = '<?= $block->getUrl('instagram/instagram/beforeConnect') ?>?client_id=' + clientId + '&client_secret=' + clientSecret;
        })
    })
</script>
