  <div class="custom-container">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="<?php echo $this->getViewFileUrl('images/banner.jpg'); ?>" alt="" />
        </div>
        <div class="item">
          <img src="<?php echo $this->getViewFileUrl('images/banner2.jpg'); ?>" alt="" />
        </div>
        <div class="item">
          <img src="<?php echo $this->getViewFileUrl('images/banner3.jpg'); ?>" alt="" />
        </div>
      </div>
    </div>
  </div>

  <!-- powder color -->
  <div class="color-powder">
    <div class="custom-container">
      <div class="row">
        <div class="col-sm-6"><img src="<?php echo $this->getViewFileUrl('images/vegan.jpg'); ?>" class="img-responsive" alt="" /></div>
        <div class="col-sm-6"><img src="<?php echo $this->getViewFileUrl('images/tierv.jpg'); ?>" class="img-responsive" alt="" /></div>
      </div>
    </div>
  </div>

  <!-- 4modals -->
  <div class="color-powder">
    <div class="custom-container">
      <ul class="imglist">
        <li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/pro1.jpg'); ?>" class="img-responsive" alt="" /></a></li>
        <li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/pro2.jpg'); ?>" class="img-responsive" alt="" /></a></li>
        <li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/pro3.jpg'); ?>" class="img-responsive" alt="" /></a></li>
        <li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/pro4.jpg'); ?>" class="img-responsive" alt="" /></a></li>
      </ul>
    </div>
  </div>

  <!-- 5 modals -->
  <div class="midsection">
    <div class="custom-container">
      <h2 class="title">Teile deinen Look #exurbecosmetics </h2>
      <ul class="modallist">
        <li><a href="#">
          <img src="<?php echo $this->getViewFileUrl('images/teil1.jpg'); ?>" class="img-responsive" alt="" />
          <div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
        </a></li>
        <li><a href="#">
          <img src="<?php echo $this->getViewFileUrl('images/teil2.jpg'); ?>" class="img-responsive" alt="" />
          <div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
        </a></li>
        <li><a href="#">
          <img src="<?php echo $this->getViewFileUrl('images/teil3.jpg'); ?>" class="img-responsive" alt="" />
          <div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
        </a></li>
        <li><a href="#">
          <img src="<?php echo $this->getViewFileUrl('images/teil4.jpg'); ?>" class="img-responsive" alt="" />
          <div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
        </a></li>
        <li><a href="#">
          <img src="<?php echo $this->getViewFileUrl('images/teil5.jpg'); ?>" class="img-responsive" alt="" />
          <div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
        </a></li>
      </ul>
    </div>
  </div>

  <!-- 3 products -->
  <div class="midsection product-list">
    <div class="custom-container">
      <h2 class="title">Unsere Favoriten</h2>
      <ul class="prolist">
        <li>
          <div class="imgbox"><a href="#"><img src="<?php echo $this->getViewFileUrl('images/unsere1.jpg'); ?>" alt="" /></a></div>
          <h3><a href="#">The Smokey Eye Look - Purple</a></h3>
          <p>Lidschatten</p>
          <div class="price">CHF 55.00 </div>
          <a href="#" class="btn">Add To Cart</a>
        </li>
        <li>
          <div class="imgbox"><a href="#"><img src="<?php echo $this->getViewFileUrl('images/unsere2.jpg'); ?>" alt="" /></a></div>
          <h3><a href="#">The Smokey Eye Look - Purple</a></h3>
          <p>Lidschatten</p>
          <div class="price">CHF 55.00 </div>
          <a href="#" class="btn">Add To Cart</a>
        </li>
        <li>
          <div class="imgbox"><a href="#"><img src="<?php echo $this->getViewFileUrl('images/unsere3.jpg'); ?>" alt="" /></a></div>
          <h3><a href="#">The Smokey Eye Look - Purple</a></h3>
          <p>Lidschatten</p>
          <div class="price">CHF 55.00 </div>
          <a href="#" class="btn">Add To Cart</a>
        </li>
      </ul>
    </div>
  </div>

  <!-- 6 options -->
  <div class="midsection product-list deine">
    <div class="custom-container">
      <h3 class="title"><span>Deine Vorteile</span></h3>
      <ul class="botmlist">
        <li>
          <img src="<?php echo $this->getViewFileUrl('images/deine1.jpg'); ?>" alt="" />
          <h4>100% Vegan</h4>
          <p>Frei von Inhaltsstoffen tierischen Ursprungs. Alle Formulierungen sind vegan.</p>
        </li>
        <li>
          <img src="<?php echo $this->getViewFileUrl('images/deine2.jpg'); ?>" alt="" />
          <h4>Ohne Tierversuche</h4>
          <p>Hergestellt ohne Tierleid. Alle Produkte und Inhaltsstoffe sind frei von Tierversuchen.</p>
        </li>
        <li>
          <img src="<?php echo $this->getViewFileUrl('images/deine3.jpg'); ?>" alt="" />
          <h4>Kostenloser Versand</h4>
          <p>Deine Bestellung erhälst du immer versandkostenfrei. Ohne Mindest- bestellwert.</p>
        </li>
        <li>
          <img src="<?php echo $this->getViewFileUrl('images/deine4.jpg'); ?>" alt="" />
          <h4>Heute bestellt Morgen geliefert</h4>
          <p>Bestellungen bis 14:00 werden noch gleichen Tags mit A-Post versandt.</p>
        </li>
        <li>
          <img src="<?php echo $this->getViewFileUrl('images/deine5.jpg'); ?>" alt="" />
          <h4>Kauf auf Rechnung</h4>
          <p>Einfach und bequem auf Rechnung bestellen. Ohne Gebühren und Zusatzkosten.</p>
        </li>
        <li>
          <img src="<?php echo $this->getViewFileUrl('images/deine6.jpg'); ?>" alt="" />
          <h4>30 Tage Rückgaberecht</h4>
          <p>Ungeöffnete Ware kannst Du innert 30 Tagen an uns zurücksenden.</p>
        </li>
      </ul>
    </div>
  </div>