<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_className = $block->getCssClass();
$blockObj= $block->getLayout()->createBlock('Favourite\FProduct\Block\CProduct');
$block_product= $block->getLayout()->createBlock('Favourite\FProduct\Block\FProduct');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
$_product=$currentProduct = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
?>
<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$_product = $block->getProduct();

	$product_id = $_product->getId();



	$productObj = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);
	$colorOption = $productObj->getResource()->getAttribute('releted_color')->getFrontend()->getValue($productObj);
	$colorOptionId = $_product->getResource()->getAttribute('releted_color')->getOptionId($colorOption);
	$attr = $productObj->getResource()->getAttribute('releted_color');
  $current_product_code="";

	if ($attr->usesSource()) {
		$attributeId = $attr->getSource()->getOptionId($colorOption);
		$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
		$connection = $resource->getConnection();
		$tableName = $resource->getTableName('eav_attribute_option_swatch');
    //echo $attributeId;
    if($attributeId!=""){
		$sql = "Select * FROM " . $tableName." where option_id = ".$attributeId;
		$result_query = $connection->fetchAll($sql);
		$current_product_code=$productHexCode = $result_query[0]['value'];
    }
	}
	//echo $productHexCode;
	?>

	<?php   if($attributeId!=""){ ?>
	<div class="color_tab">
			<div class="selected">
			<label>Gewählte Farbe</label>
		<div class="color-txt">
		<span><?php echo $_product->getName(); ?></span>
		<?= $colorOption;?>
		</div>
		<div class="attribDiv" style="background-color:<?=@$productHexCode?>;"></div>
		</a>
	</div>

<?php } ?>
<?php
$categories = $_product->getCategoryIds(); /*will return category ids array*/

// ============================== for Tablet =======================================================================================
foreach($categories as $category){

  $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
  $cats[] =  $cat->getId();
  }
//print_r($cats);
$check = array();
@$check[0] = @$cats[0];
$Fblock = $this->getLayout()->createBlock('Favourite\FProduct\Block\CProduct');
$productCollection = $Fblock->getCategoryProduct($check);
?>
<div class="category_product">
  <ul>
<?php
foreach ($productCollection as $product) {
  // $img = $helperImport->init($product, 'product_page_image_small')
  //             ->setImageFile($product->getSmallImage()) // image,small_image,thumbnail
  //             ->resize(380)
  //             ->getUrl();
               $productHexCode = '';
  $product_id = $product->getId();
  if($productHexCode!=="undefined"){
  try{
  $objectMansager = \Magento\Framework\App\ObjectManager::getInstance();
  $productObj = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);
  $colorOption = $productObj->getResource()->getAttribute('releted_color')->getFrontend()->getValue($productObj);
  $colorOptionId = $product->getResource()->getAttribute('releted_color')->getOptionId($colorOption);
  $attr = $productObj->getResource()->getAttribute('releted_color');

  if ($attr->usesSource()) {
    $attributeId = $attr->getSource()->getOptionId($colorOption);
    $resource = $objectMansager->get('Magento\Framework\App\ResourceConnection');
    $connection = $resource->getConnection();
    $tableName = $resource->getTableName('eav_attribute_option_swatch');
    $sql = "Select * FROM " . $tableName." where option_id = ".$attributeId;
    $result_query = $connection->fetchAll($sql);
    $productHexCode = $result_query[0]['value'];
  }
  }catch(Exception $e){}

    ?><?php
  if($product_id==$product->getId()){

  ?>
    <li><a  href="<?php echo $product->getProductUrl(); ?>">
      <!-- <img width="20px" height="20px" src="<?php //echo $img; ?>" /> -->
    <div class="attribDiv<?=($current_product_code==$productHexCode)?" active":"";?>" style="width:20px;height:20px;background-color:<?=$productHexCode?>;display: inline-block;" val="<?=$product_id?>"></div>
  </a></li>
  <?php
    }else{
  ?>
  <li>	<a  href="<?php echo $product->getProductUrl(); ?>">
      <!-- <img width="30px" height="30px" src="<?php //echo $img; ?>" /> -->

    <div class="attribDiv active selected" style="width:20px;height:20px;background-color:<?=$productHexCode?>;display: inline-block;"></div>
  </a></li>
  <?php
    }
}


}

?></ul>
</div>	</div>
 <!-- ============================== End Tablet ======================================================================================= -->


  <!-- ============================== Start Mobile ======================================================================================= -->

  <div class="wrapper mobile_owl">
    <ul class="owl-carousel">
  <?php
  foreach ($productCollection as $product) {
    // $img = $helperImport->init($product, 'product_page_image_small')
    //             ->setImageFile($product->getSmallImage()) // image,small_image,thumbnail
    //             ->resize(380)
    //             ->getUrl();
                 $productHexCode = '';
    $product_id = $product->getId();
    if($productHexCode!=="undefined"){
    try{
    $objectMansager = \Magento\Framework\App\ObjectManager::getInstance();
    $productObj = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);
    $colorOption = $productObj->getResource()->getAttribute('releted_color')->getFrontend()->getValue($productObj);
    $colorOptionId = $product->getResource()->getAttribute('releted_color')->getOptionId($colorOption);
    $attr = $productObj->getResource()->getAttribute('releted_color');

    if ($attr->usesSource()) {
      $attributeId = $attr->getSource()->getOptionId($colorOption);
      $resource = $objectMansager->get('Magento\Framework\App\ResourceConnection');
      $connection = $resource->getConnection();
      $tableName = $resource->getTableName('eav_attribute_option_swatch');
      $sql = "Select * FROM " . $tableName." where option_id = ".$attributeId;
      $result_query = $connection->fetchAll($sql);
      $productHexCode = $result_query[0]['value'];
    }
    }catch(Exception $e){}

      ?><?php
    if($product_id==$product->getId()){

    ?>
      <li><a  href="<?php echo $product->getProductUrl(); ?>">
        <!-- <img width="20px" height="20px" src="<?php //echo $img; ?>" /> -->
      <div class="attribDiv<?=($current_product_code==$productHexCode)?" active":"";?>" style="width:40px;height:40px;background-color:<?=$productHexCode?>;display: inline-block;" val="<?=$product_id?>"></div>
    </a></li>
    <?php
      }else{
    ?>
    <li>	<a  href="<?php echo $product->getProductUrl(); ?>">
        <!-- <img width="30px" height="30px" src="<?php //echo $img; ?>" /> -->

      <div class="attribDiv active selected" style="width:40px;height:40px;background-color:<?=$productHexCode?>;display: inline-block;"></div>
    </a></li>
    <?php
      }
  }


  }

  ?></ul>
  </div>


  <!-- ============================== End Mobile ======================================================================================= -->

  <!-- <div class="wrapper">
    <ul class="owl-carousel">
      <li><img src="http://placehold.it/1300x780" alt=""></li>
      <li><img src="http://placehold.it/1300x780" alt=""></li>
      <li><img src="http://placehold.it/1300x780" alt=""></li>
      <li><img src="http://placehold.it/1300x780" alt=""></li>
      <li><img src="http://placehold.it/1300x780" alt=""></li>
    </ul>
  </div> -->

<div class="description_mobile">

	      <div class="vegan_box_RG">
	        <div class="vegan">
	            <div class="img-box"><img src="<?php echo $this->getViewFileUrl('images/svg/vigan1.svg'); ?>"" class="img-flower"></div>
	            <span class="img-flower-txt">Vegan</span>
	        </div>
	        <div class="vegan">
	            <div class="img-box"><img src="<?php echo $this->getViewFileUrl('images/svg/rabit1.svg'); ?>" class="img-rabbit"></div>
	            <span class="img-rabbit-txt">Ohne Tierversuche</span>
	        </div>
	      </div>


<?php echo $this->getLayout()->createBlock("Magento\Catalog\Block\Product\View\Description")->setTemplate("Magento_Catalog::product/view/product_description_mobile.phtml")->toHtml();?>
</div>


	<?php //echo $this->createBlock("Magento\Catalog\Block\Product\View")->setTemplate("Magento_Catalog::product/view/form.phtml")->toHtml(); ?>
<?php //echo $this->createBlock("Magento\Catalog\Block\Product\View\Price")->setTemplate("Magento_Catalog::product/view/form.phtml")->toHtml(); ?>
<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Favourite_FProduct::vegan_beauty.phtml")->toHtml();?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>

    <div class="product info detailed">
        <!-- 5 modals -->
        <div class="pin-share-blk">
            <div class="custom-container">
              <h2 class="title">Teile deinen Look <span>#exurbecosmetics</span> </h2>
								<?php echo $this->setTemplate("Magento_Theme::html/instagram_slider.phtml")->toHtml() ?>
              <ul class="modallist">
                <li><a href="#">
                  <img src="<?php echo $this->getViewFileUrl('images/teil1.jpg'); ?>" class="img-responsive" alt="" />
                  <div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
                </a></li>
                <li><a href="#">
                  <img src="<?php echo $this->getViewFileUrl('images/teil2.jpg'); ?>" class="img-responsive" alt="" />
                  <div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
                </a></li>
                <li><a href="#">
                  <img src="<?php echo $this->getViewFileUrl('images/teil3.jpg'); ?>" class="img-responsive" alt="" />
                  <div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
                </a></li>
                <li><a href="#">
                  <img src="<?php echo $this->getViewFileUrl('images/teil4.jpg'); ?>" class="img-responsive" alt="" />
                  <div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
                </a></li>
                <li><a href="#">
                  <img src="<?php echo $this->getViewFileUrl('images/teil5.jpg'); ?>" class="img-responsive" alt="" />
                  <div class="icon"><img src="<?php echo $this->getViewFileUrl('images/instagram.png'); ?>" alt="" /></div>
                </a></li>
              </ul>
            </div>
        </div>


        <?php $layout = $block->getLayout();
          $ratings=$blockObj->get_rating();


        ?>
        <?php $ok=0;if($ratings!=0){
          $ok=1;
        }?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active", "active": "1"}}'>

            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>

                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">

                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>

                </div>

                <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
					<div class="summeryreview" >
					 </div>
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach;?>
        </div>


    </div>
<?php endif; ?>

<div class="mobile-upsell">
	<?php echo $this->setTemplate("Magento_Catalog::product/view/upsell.phtml")->toHtml() ?>
</div>

<!-- Upsell Products -->

<?php
  if ($currentProduct)
  {
    $upSellProducts = $currentProduct->getUpSellProducts();
    //check if record is empty or not
    $count = count($upSellProducts);


    if (!empty($upSellProducts))
    { ?>
      <div class="upsell_products upsell-desktop">
      <div class="custom-container product-list top-padd-none">

      <ul class="prolist">

          <?php echo'	<h2 class="title">Das könnte dir  auch<srrong> gefallen</strong> </h2>';
      $i = 0;
      foreach ($upSellProducts as $upSellProduct)
      {
        if ($i >= 3)
        break;
        ?>
          <?php
            $productId = $upSellProduct->getId();
            $product = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
            $imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
            $productImage = $imageBlock->getImage($product, 'category_page_list');
            $currencysymbol = $objectManager->create('Magento\Directory\Model\Currency')->getCurrencySymbol();
            //
            $ratings=$blockObj->get_rating($product);

            //
          ?>
          <li>
            <?php $postParams = $block_product->getAddToCartPostParams($product); ?>
            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
               <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
               <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */echo $postParams['data']['uenc']; ?>">
                <?php echo $block->getBlockHtml('formkey')?>
                <div class="product-img">
            <a href="<?php echo $product->getProductUrl(); ?>"><?php echo $productImage->toHtml(); ?></a>
          </div>
            <h3><a href="<?php echo $product->getProductUrl(); ?>"><?php if($product) { echo $product->getName(); } ?></a></h3>
              <p class="cat-name"><?=$blockObj->get_current_product_category_name($product);?></p>


            <div class="price"><?php echo $currencysymbol.number_format($product->getPrice(), 2, '.', ''); ?></div>
            <div class="review-ratings">
            <div class="rating-summary item" itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
            <!--<span class="label rating-label"><span>Quality</span></span>-->
            <div class="rating-result" title="<?=number_format($ratings,2,'.','')?>%">
            <meta itemprop="worstRating" content="1">
            <meta itemprop="bestRating" content="100">
            <span style="width:<?=number_format($ratings,2,'.','')?>%">
            <span itemprop="ratingValue"><?=number_format($ratings,2,'.','')?>%</span>
            </span>
            </div>
            </div>
          </div>

              <button type="submit"
                      title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                      class="action tocart primary">
                  <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
              </button>
          </form>
          </li>
        <?php
        $i++;
      }
    }
  }
?>
</ul>
</div>
</div>

<?php //if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }
    </script>

    <script>
    (function  () {
        require(["jquery","owl.carousel"],function($) {
          $(".owl-carousel").owlCarousel({
							items : 5,
						  itemsDesktop : [1199,9],
						  itemsDesktopSmall : [980,9],
						  itemsTablet: [768,8],
						  itemsTabletSmall: false,
						  itemsMobile : [479,6],
						  singleItem : false,
              slideSpeed: 500,
              autoPlay: 5000,
              stopOnHover: true,
              navigation : false
            });
        });
    })();
    </script>
<?php //endif;

// echo $this->getLayout()->createBlock("Favourite\FProduct\Block\FProduct")->setTemplate("Favourite_FProduct::fproduct.phtml")->toHtml(); -->
