<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <?php echo $block->getChildHtml('checkout_cart_empty_widget'); ?>
    <p><?php /* @escapeNotVerified */ echo __('Dein Warenkorb ist leer.') ?></p>
	<p><?php /* @escapeNotVerified */ echo __('Leg los und fülle deinen Warenkorb mit den neuesten Makeup-Trends.') ?></p>
    <?php //echo __('TO THE NEWS') ?>
    <p><?php /* @escapeNotVerified */ echo __('<a href="%1">'. __('TO THE NEWS').'</a>',
            $block->escapeUrl($block->getContinueShoppingUrl())) ?></p>
    <?php echo $block->getChildHtml('shopping.cart.table.after'); ?>
    <div class="full-img-panel"><div class="thankimg"><img src="<?php echo $this->getViewFileUrl('images/thankyoubanner.jpg'); ?>" alt="" />
    <!-- <img src="<?php echo $this->getViewFileUrl('images/thankyou.jpg'); ?>" alt="" /></div> -->
</div></div>
<?php echo  $this->getLayout()->createBlock("Favourite\FProduct\Block\FProduct")->setTemplate("Favourite_FProduct::fproduct.phtml")->toHtml(); ?>
